### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by SilentImp** [FrontenderMagazine/absolute-beginners-guide-to-nodejs#1]

**Comment by efremoz** [comment]
Спасибо за пояснения!
цитирую:
Например, если вы положите изображение с именем my_image.png в эту папку, его можно будет запросить по адресу http://localhost:8080/my_image.png. 

Можно ли через сервер на nodejs  перейти на домен без порта:8080?
Что в сервере нужно прописать?
http://domen.ru/my_image.png.

**Comment by subzey** [comment]
Можно. Порт HTTP по умолчанию — 80. Соответственно, нужно в вызове `.listen()` поменять 8080 на 80.

**Comment by efremoz** [comment]
Попробывал задать порт 80, выдает такую ошибку:  

Server running at http://127.0.0.1:80/

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.start (/opt/nodejs/bin/server.js:16:31)
    at Object.<anonymous> (/opt/nodejs/bin/index.js:10:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

То есть сервер запускается, а потом что-то происходит.
На сервере несколько доменов, по порту 80 к кому домену осуществляется переход?

**Comment by subzey** [comment]
`EADDRINUSE` означает, что этот порт уже занят другим процессом. Запустить одновременно тот же Апач и Ноду на одном порту нельзя. И это не особенность конкретно Апача или Ноды, операционка просто не смогла бы понять, в какой из процессов перенаправить сетевые данные.

*Иногда вы даже можете не подозревать, что кто-то захапал себе 80 порт. Скайп, например, любит так делать.*

Как быть? Для того, чтобы два (и более) разношёрстных сервиса могли пользоваться одним портом, обычно используется nginx. Мы выставляем Апач слушать какой-нибудь незанятный порт, например, 8080. Ноду - другой незанятый, например, 8081. А nginx будет слушать по 80. Затем, когда он получит запрос, он вычленит из него хостнейм и путь, и на основе этого решит, куда дальше запрос перенаправить (настраивается в конфигах).

Из плюсов nginx: он умеет раздавать статику, и делает это очень быстро и экономно по ресурсам и этим прекрасно дополняет ноду, поэтому есть смысл использовать его даже если кроме ноды ничего нет.

Ещё, когда вы будете выкатывать это в продакшне на линуксе, вы можете встретить ошибку `ENOENT` (кажется), это означает, что у процесса недостаточно прав. Но это уже совсем выходит за рамки тематики статьи, уже два моих коммента сами тянут на статью по объёму. :)

**Comment by efremoz** [comment]
subzey  Спасибо за подробности! Было бы здорово прочитать такую статью, пошаговая настройка работы node и nginx на linux.

**Comment by lancedikson** [comment]
@efremoz, есть [вот такой туториал от DO](https://www.digitalocean.com/community/tutorials/how-to-host-multiple-node-js-applications-on-a-single-vps-with-nginx-forever-and-crontab).

**Comment by efremoz** [comment]
Благодарю!

**Comment by vhajmik** [comment]
Спасибо, помогла статья.
Попробовал также вот это https://www.npmjs.com/package/react-ui-builder
Оченно легко набрасывать UI компоненты на страницу.

**Comment by AlekseyPriz** [comment]
Запустил сервер из раздела "Делаем что-нибудь полезное — HTTP-сервер". Спасибо, работает, а как теперь его удалить?

**Comment by iamstarkov** [comment]
@AlekseyPriz руками?

**Comment by 36serg6** [comment]
Объясните пожалуйста, зачем делается два раза parseInt() в my_parser.js?
